<?php

namespace App\Support;

/**
 * Reads the shared icon map generated by `npm run icons`
 * (resources/icons/icons.json) for use in Blade views.
 */
final class Icons
{
    /** @var array<string,string>|null */
    private static ?array $icons = null;

    public static function get(string $name): string
    {
        if (self::$icons === null) {
            $path = resource_path('icons/icons.json');
            self::$icons = is_file($path) ? (json_decode((string) file_get_contents($path), true) ?: []) : [];
        }

        return self::$icons[$name] ?? self::$icons['circle-alert'] ?? '';
    }
}
